export const products = [
  {title: 'All', category: 'all'},
  {title: 'Supermarket', category: 'groceries'},
  {title: 'Health & Beauty', category: 'beauty'},
  {title: 'Home & Office', category: 'furniture'},
  {title: 'Groceries', category: 'groceries'},
  {title: 'Bath', category: 'beauty'},
  {title: 'Bedding', category: 'furniture'},
  {title: 'Home Decor', category: 'fragrances'},
  {title: 'Home Furniture', category: 'beauty'},
  {title: 'Wall Art', category: 'furniture'},
  {title: 'Body Care', category: 'fragrances'},
  {title: 'Accessories', category: 'furniture'},
  {title: 'Vacuums & Floor Care', category: 'beauty'},
  {title: 'Office Products', category: 'furniture'},
  {title: 'Skin Care Materials', category: 'beauty'},
  {title: 'Office Furniture & Lighting', category: 'furniture'},
  {title: 'Fashion', category: 'beauty'},
  {title: 'Office & School Supplies', category: 'furniture'},
  {title: 'Other categories', category: 'others'},
]