export const products = [
  'All',
  'Supermarket',
  'Health & Beauty',
  'Home & Office',
  'Home & Kitchen',
  'Bath',
  'Bedding',
  'Home Decor',
  'Home Furniture',
  'Vacuums & Floor Care',
  'Wall Art',
  'Small Appliances',
  'Cutlery & Knife Accessories',
  'Office Products',
  'Office & School Supplies',
  'Office Furniture & Lighting',
  'Packaging Materials',
  'Home & Office Furniture',
  'Kitchen & Dining',
  'Lighting',
  'Stationery',
  'Storage & Organization',
  'Appliances',
  'Phones & Tablets',
  'Computing',
  'Electronics',
  'Fashion',
  'Baby Products',
  'Gaming',
  'Sporting Goods',
  'Other categories'
]